//! Transactional email service.
//!
//! Sends lifecycle emails (verification, password reset, welcome) through the
//! [Resend](https://resend.com) API.  If `RESEND_API_KEY` is absent or empty
//! every send call returns an error immediately — useful for local dev where
//! emails are not needed.

use reqwest::Client;
use serde::{Deserialize, Serialize};
use std::sync::Arc;
use tracing::{error, info};

#[derive(Debug, Serialize)]
struct ResendEmailRequest {
    from: String,
    to: String,
    subject: String,
    html: String,
}

#[derive(Debug, Deserialize)]
struct ResendEmailResponse {
    id: String,
}

/// Wraps the Resend HTTP API for sending transactional emails.
///
/// Constructed once at startup and shared via `Arc<EmailService>`.  The
/// underlying `reqwest::Client` is also behind an `Arc` so cloning the
/// service is cheap.
pub struct EmailService {
    client: Arc<Client>,
    api_key: String,
    from_email: String,
}

impl EmailService {
    /// Create a new service instance.
    ///
    /// - `api_key` — Resend API key (`RESEND_API_KEY`); pass an empty string
    ///   to disable sending in environments where email isn't needed.
    /// - `from_email` — "From" address used for all outbound mail
    ///   (`RESEND_FROM_EMAIL`).
    pub fn new(api_key: String, from_email: String) -> Self {
        Self {
            client: Arc::new(Client::new()),
            api_key,
            from_email,
        }
    }

    /// Send an email verification link to a newly registered user.
    ///
    /// The `token` is a short-lived opaque string generated by the auth
    /// service.  Returns the Resend message ID on success, or an error
    /// message string on failure.
    pub async fn send_verification_email(
        &self,
        to_email: String,
        token: String,
    ) -> Result<String, String> {
        if self.api_key.is_empty() {
            return Err("RESEND_API_KEY not configured".to_string());
        }

        // TODO: move to config — domain differs between staging and production
        let verification_link = format!("https://m.cookest.app/verify?token={}", token);

        let request = ResendEmailRequest {
            from: self.from_email.clone(),
            to: to_email.clone(),
            subject: "Verify your Cookest account".to_string(),
            html: self.verification_email_html(&verification_link),
        };

        match self.send_email(request).await {
            Ok(response_id) => {
                info!("Verification email sent to {}: {}", to_email, response_id);
                Ok(response_id)
            }
            Err(e) => {
                error!("Failed to send verification email: {}", e);
                Err(e)
            }
        }
    }

    /// Send a password-reset link to the requesting user.
    ///
    /// The `token` is time-limited and single-use.  Returns the Resend
    /// message ID on success.
    pub async fn send_password_reset_email(
        &self,
        to_email: String,
        token: String,
    ) -> Result<String, String> {
        if self.api_key.is_empty() {
            return Err("RESEND_API_KEY not configured".to_string());
        }

        // TODO: move to config — domain differs between staging and production
        let reset_link = format!("https://m.cookest.app/reset-password?token={}", token);

        let request = ResendEmailRequest {
            from: self.from_email.clone(),
            to: to_email.clone(),
            subject: "Reset your Cookest password".to_string(),
            html: self.password_reset_email_html(&reset_link),
        };

        match self.send_email(request).await {
            Ok(response_id) => {
                info!("Password reset email sent to {}: {}", to_email, response_id);
                Ok(response_id)
            }
            Err(e) => {
                error!("Failed to send password reset email: {}", e);
                Err(e)
            }
        }
    }

    /// Send a branded welcome email after a user's first successful login
    /// (or immediately after email verification, depending on the auth flow).
    ///
    /// `name` is the display name used in the email greeting.
    pub async fn send_welcome_email(
        &self,
        to_email: String,
        name: String,
    ) -> Result<String, String> {
        if self.api_key.is_empty() {
            return Err("RESEND_API_KEY not configured".to_string());
        }

        let request = ResendEmailRequest {
            from: self.from_email.clone(),
            to: to_email.clone(),
            subject: "Welcome to Cookest!".to_string(),
            html: self.welcome_email_html(&name),
        };

        match self.send_email(request).await {
            Ok(response_id) => {
                info!("Welcome email sent to {}: {}", to_email, response_id);
                Ok(response_id)
            }
            Err(e) => {
                error!("Failed to send welcome email: {}", e);
                Err(e)
            }
        }
    }

    async fn send_email(&self, request: ResendEmailRequest) -> Result<String, String> {
        match self
            .client
            .post("https://api.resend.com/emails")
            .header("Authorization", format!("Bearer {}", self.api_key))
            .json(&request)
            .send()
            .await
        {
            Ok(response) => match response.json::<ResendEmailResponse>().await {
                Ok(data) => Ok(data.id),
                Err(e) => Err(format!("Failed to parse Resend response: {}", e)),
            },
            Err(e) => Err(format!("Failed to send email via Resend: {}", e)),
        }
    }

    fn verification_email_html(&self, verification_link: &str) -> String {
        format!(
            r#"<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <style>
      body {{ font-family: 'Inter', 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #F5F5F0; margin: 0; padding: 40px 20px; }}
      .container {{ max-width: 500px; margin: 0 auto; background-color: #FFFFFF; border: 1px solid #E4EBE0; border-radius: 12px; overflow: hidden; }}
      .header {{ text-align: center; padding: 30px 20px; background-color: #FAFAF6; border-bottom: 1px solid #E4EBE0; }}
      h1 {{ font-family: 'Playfair Display', serif; color: #1C3A2A; margin: 0; font-size: 24px; }}
      .content {{ padding: 30px 20px; color: #3D5040; line-height: 1.6; }}
      .button {{ 
        background-color: #7A9A65; 
        color: #FFFFFF; 
        padding: 14px 24px; 
        text-decoration: none; 
        border-radius: 8px; 
        display: block; 
        text-align: center;
        font-weight: 600;
        margin: 24px 0;
      }}
      .footer {{ text-align: center; color: #7A8E74; font-size: 13px; padding: 20px; border-top: 1px solid #E4EBE0; background-color: #FAFAF6; }}
      .link-text {{ word-break: break-all; color: #7A8E74; font-size: 13px; margin-top: 8px; }}
    </style>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <h1>Welcome to Cookest!</h1>
      </div>
      <div class="content">
        <p>Thank you for signing up. Please verify your email address to get started with intelligent meal planning.</p>
        <a href="{}" class="button">Verify Email</a>
        <p style="font-size: 14px; margin-top: 30px;">Or copy and paste this link in your browser:</p>
        <p class="link-text">{}</p>
      </div>
      <div class="footer">
        <p>© 2026 Cookest. All rights reserved.</p>
      </div>
    </div>
  </body>
</html>"#,
            verification_link, verification_link
        )
    }

    fn password_reset_email_html(&self, reset_link: &str) -> String {
        format!(
            r#"<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <style>
      body {{ font-family: 'Inter', 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #F5F5F0; margin: 0; padding: 40px 20px; }}
      .container {{ max-width: 500px; margin: 0 auto; background-color: #FFFFFF; border: 1px solid #E4EBE0; border-radius: 12px; overflow: hidden; }}
      .header {{ text-align: center; padding: 30px 20px; background-color: #FAFAF6; border-bottom: 1px solid #E4EBE0; }}
      h1 {{ font-family: 'Playfair Display', serif; color: #1C3A2A; margin: 0; font-size: 24px; }}
      .content {{ padding: 30px 20px; color: #3D5040; line-height: 1.6; }}
      .button {{ 
        background-color: #7A9A65; 
        color: #FFFFFF; 
        padding: 14px 24px; 
        text-decoration: none; 
        border-radius: 8px; 
        display: block; 
        text-align: center;
        font-weight: 600;
        margin: 24px 0;
      }}
      .footer {{ text-align: center; color: #7A8E74; font-size: 13px; padding: 20px; border-top: 1px solid #E4EBE0; background-color: #FAFAF6; }}
      .warning {{ background-color: #FAFAF6; padding: 16px; border: 1px solid #E4EBE0; border-radius: 8px; margin-top: 24px; font-size: 13px; color: #7A8E74; }}
      .link-text {{ word-break: break-all; color: #7A8E74; font-size: 13px; margin-top: 8px; }}
    </style>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <h1>Password Reset</h1>
      </div>
      <div class="content">
        <p>We received a request to reset your Cookest password. Click the button below to set a new password.</p>
        <a href="{}" class="button">Reset Password</a>
        <p style="font-size: 14px; margin-top: 30px;">Or copy and paste this link in your browser:</p>
        <p class="link-text">{}</p>
        <div class="warning">
          <p style="margin: 0;"><strong>Note:</strong> This link will expire in 24 hours. If you didn't request a password reset, please safely ignore this email.</p>
        </div>
      </div>
      <div class="footer">
        <p>© 2026 Cookest. All rights reserved.</p>
      </div>
    </div>
  </body>
</html>"#,
            reset_link, reset_link
        )
    }

    fn welcome_email_html(&self, name: &str) -> String {
        format!(
            r#"<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <style>
      body {{ font-family: 'Inter', 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #F5F5F0; margin: 0; padding: 40px 20px; }}
      .container {{ max-width: 500px; margin: 0 auto; background-color: #FFFFFF; border: 1px solid #E4EBE0; border-radius: 12px; overflow: hidden; }}
      .header {{ text-align: center; padding: 30px 20px; background-color: #FAFAF6; border-bottom: 1px solid #E4EBE0; }}
      h1 {{ font-family: 'Playfair Display', serif; color: #1C3A2A; margin: 0; font-size: 24px; }}
      .content {{ padding: 30px 20px; color: #3D5040; line-height: 1.6; }}
      .button {{ 
        background-color: #7A9A65; 
        color: #FFFFFF; 
        padding: 14px 24px; 
        text-decoration: none; 
        border-radius: 8px; 
        display: block; 
        text-align: center;
        font-weight: 600;
        margin: 24px 0;
      }}
      .footer {{ text-align: center; color: #7A8E74; font-size: 13px; padding: 20px; border-top: 1px solid #E4EBE0; background-color: #FAFAF6; }}
      .features {{ margin: 24px 0; padding: 20px; background-color: #FAFAF6; border-radius: 8px; border: 1px solid #E4EBE0; }}
      .features h3 {{ font-family: 'Playfair Display', serif; color: #1C3A2A; margin-top: 0; }}
      .feature {{ margin: 12px 0; padding-left: 24px; position: relative; color: #3D5040; }}
      .feature::before {{ content: "✓"; position: absolute; left: 0; color: #7A9A65; font-weight: bold; }}
    </style>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <h1>Welcome, {}!</h1>
      </div>
      <div class="content">
        <p>We're excited to have you join Cookest. Start exploring intelligent meal planning, smart grocery lists, and personalized recipes.</p>
        <div class="features">
          <h3>Get started with:</h3>
          <div class="feature">AI-powered meal planning</div>
          <div class="feature">Inventory management</div>
          <div class="feature">Shopping list optimization</div>
          <div class="feature">Recipe discovery</div>
        </div>
        <a href="https://m.cookest.app" class="button">Open Cookest</a>
      </div>
      <div class="footer">
        <p>© 2026 Cookest. All rights reserved.</p>
      </div>
    </div>
  </body>
</html>"#,
            name
        )
    }
}
